name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    needs: release
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploying
        run: |
        sleep 10
        ps
        pwd
        env

