name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploying
        run: sleep 10

      - name: pwd
        run: pwd

      - name: Env
        run: env

